apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  labels:
    app: auth    
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        # image: 715514482422.dkr.ecr.us-east-2.amazonaws.com/auth-srv:latest
        image: vunguyen88/todoeks-auth
        ports:
        - name: auth
          containerPort: 8000
        env:
        - name: AWS_IAM_AUTH_SERVICE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: authserviceaccesskey
              key: auth_service_access_key
        - name: AWS_IAM_AUTH_SERVICE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authservicesecretkey
              key: auth_service_secret_key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt
              key: jwt_secret


        
